### PR TITLE
update for Laravel Passport API requirements

### PR DESCRIPTION
**Pull request by fritsstegmann**
I get a 422 error with a new Laravel 6, Nova 2.5 and Passport 7.5

### CODE REVIEW

**Comment by mikebronner** [comment]
Thanks for posting this! I haven't tested with the latest versions yet. I will take a look at this as soon as possible. :)

**Comment by fritsstegmann** [comment]
Hi. I was wondering if there was any progress on this?

**Comment by mikebronner** [comment]
@fritsstegmann sorry for the delay. I've been really swamped lately. I have been using it without issue on my apps, but perhaps my passport version isn't current.

**Comment by mikebronner** [comment]
@fritsstegmann Please give release 0.3.0 a try and let me know how it works for you.

**Pull request merged**
